title: Citizens Summons
email: info@citizenssummons.org
description: >- # this means to ignore newlines until "baseurl:"
 Adherents to the Sixth Declaration of the Lacandon Jungle.
baseurl: /about/
url: http://citizenssummons.org
twitter_username: CitizensSummons
facebook_username: CitizensSummons
root: /octo-5

# Build settings
theme: minima
plugins:
  - jekyll-feed

colors:
  black:     '#000000'
  dark-blue: '#1B262C'
  white:     '#ffffff'
  red:       '#C40A25'
  blue:      '#253B56'
  salmon:    '#F89E77'

include: [_pages]
permalink: pretty

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /blog/:categories/:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
