title: Citizens Summons
email: info@citizenssummons.org
description: >- # this means to ignore newlines until "baseurl:"
 Adherents to the Sixth Declaration of the Lacandon Jungle.
baseurl: /about
twitter_username: CitizensSummons
facebook_username: CitizensSummons

# Build settings
theme: minima
plugins:
  - jekyll-feed

colors:
  black:     '#000000'
  dark-blue: '#1B262C'
  white:     '#ffffff'
  red:       '#C40A25'
  blue:      '#253B56'
  salmon:    '#F89E77'

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
